import bcrypt from "bcryptjs";

export const DEFAULT_PASSWORD_HASH = bcrypt.hashSync("password123", 10);

export const SEED_USERS = [
  {
    id: "u_hamza_001",
    email: "hamza@orba.app",
    username: "syedhamza",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "Syed Hamza",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    bio: "Building high-performance real-time software where conversations orbit people.",
    website: "https://orba.app",
    location: "San Francisco, CA",
  },
  {
    id: "u_elena_002",
    email: "elena@cerebro.ai",
    username: "elena",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "Dr. Elena Vance",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1200&auto=format&fit=crop&q=80",
    bio: "Principal AI Alignment Researcher. Investigating interpretability in large multimodal foundation models and geometric deep learning.",
    website: "https://elenavance.ai",
    location: "Zurich, Switzerland",
  },
  {
    id: "u_marcus_003",
    email: "marcus@linearforge.dev",
    username: "mthorne",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "Marcus Thorne",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80",
    bio: "Staff Product Designer & Creative Technologist. Obsessed with micro-interactions, dark interfaces, and tactile developer tools.",
    website: "https://thorne.design",
    location: "Stockholm, Sweden",
  },
  {
    id: "u_aria_004",
    email: "aria@ionquantum.io",
    username: "ariasterling",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "Aria Sterling",
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1200&auto=format&fit=crop&q=80",
    bio: "Quantum Hardware Engineer @ IonQ. Coherence times, Rydberg atom arrays, and topological error-correcting codes.",
    website: "https://aria.quantum.io",
    location: "Boston, MA",
  },
  {
    id: "u_kaelen_005",
    email: "kaelen@rustdb.org",
    username: "kaelen",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "Kaelen Patel",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80",
    bio: "Distributed Databases Core Eng. Writing lockless concurrency primitives, io_uring engines, and Raft consensus in Rust.",
    website: "https://github.com/kaelenp",
    location: "Seattle, WA",
  },
  {
    id: "u_sophia_006",
    email: "sophia@apexcloud.io",
    username: "sophialin",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "Sophia Lin",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=256&auto=format&fit=crop&q=80",
    bio: "VP Engineering @ Apex Distributed. Multi-region edge architecture, sub-millisecond p99s, and high-availability systems.",
    website: "https://sophialin.tech",
    location: "Singapore",
  },
  {
    id: "u_david_007",
    email: "david@zkproofs.org",
    username: "davidzhao",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "David Zhao",
    avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=256&auto=format&fit=crop&q=80",
    bio: "Cryptographic protocol designer. Zero-knowledge SNARKs, recursive proving circuits, and trustless privacy layers.",
    website: "https://zkzhao.dev",
    location: "New York, NY",
  },
  {
    id: "u_maya_008",
    email: "maya@typefoundry.design",
    username: "mayaross",
    role: "USER" as const,
    is_verified: false,
    is_private: false,
    is_suspended: false,
    display_name: "Maya Ross",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=256&auto=format&fit=crop&q=80",
    bio: "Editorial Art Director & Type Designer. Exploring variable fonts, optical sizing, and spatial typography in UI.",
    website: "https://mayaross.studio",
    location: "London, UK",
  },
  {
    id: "u_liam_009",
    email: "liam@ebpfrealtime.net",
    username: "liamoc",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "Liam O'Connor",
    avatar_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=256&auto=format&fit=crop&q=80",
    bio: "Kernel bypass, eBPF telemetry, and million-concurrent-connection WebSockets state synchronizer.",
    website: "https://liamoc.tech",
    location: "Dublin, Ireland",
  },
  {
    id: "u_zoe_010",
    email: "zoe@roboticsperception.ai",
    username: "zoechen",
    role: "USER" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "Zoe Chen",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=256&auto=format&fit=crop&q=80",
    bio: "Autonomous mobile robotics & NeRF SLAM perception. Giving robots spatial awareness in dynamic human spaces.",
    website: "https://zoechen.robotics",
    location: "Austin, TX",
  },
  {
    id: "u_admin_099",
    email: "sentinel@orba.app",
    username: "sentinel",
    role: "ADMIN" as const,
    is_verified: true,
    is_private: false,
    is_suspended: false,
    display_name: "ORBA Sentinel",
    avatar_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=256&auto=format&fit=crop&q=80",
    bio: "Automated integrity & trust monitoring service for the ORBA Social Orbit.",
    website: "https://orba.app/security",
    location: "Orbit Alpha Core",
  }
];

export const SEED_CIRCLES = [
  {
    id: "c_distributed_systems",
    name: "Distributed Systems & Rust",
    slug: "distributed-systems",
    description: "Consensus algorithms, Raft, Paxos, eBPF, LSM storage engines, and zero-overhead memory-safe concurrency.",
    avatar_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80",
    owner_id: "u_kaelen_005",
    member_count: 1420,
    is_private: false,
  },
  {
    id: "c_ai_alignment",
    name: "AI Alignment & Multimodal Research",
    slug: "ai-alignment",
    description: "Mechanistic interpretability, safety evaluations, representation steering, and foundational neural scaling.",
    avatar_url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    owner_id: "u_elena_002",
    member_count: 2890,
    is_private: false,
  },
  {
    id: "c_nextgen_ui",
    name: "Tactile & Editorial UI Engineering",
    slug: "nextgen-ui",
    description: "High-craft digital interfaces, sub-frame motion fidelity, spatial typography, and dark-first ergonomics.",
    avatar_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80",
    owner_id: "u_marcus_003",
    member_count: 1980,
    is_private: false,
  },
  {
    id: "c_quantum_frontier",
    name: "Quantum Computing & Photonics",
    slug: "quantum-frontier",
    description: "Superconducting qubits, trapped-ion gates, topological quantum error correction, and quantum algorithms.",
    avatar_url: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1200&auto=format&fit=crop&q=80",
    owner_id: "u_aria_004",
    member_count: 940,
    is_private: false,
  },
  {
    id: "c_zero_knowledge",
    name: "Applied Cryptography & ZK",
    slug: "applied-zk",
    description: "PLONK, STARKs, recursive SNARK verification, verifiable computation, and cryptographic privacy primitives.",
    avatar_url: "https://images.unsplash.com/photo-1516245834210-c4c142787335?w=256&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80",
    owner_id: "u_david_007",
    member_count: 1150,
    is_private: false,
  },
];
